// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/comm/store_obj.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALEntry_Operation int32

const (
	WALEntry_UPDATE WALEntry_Operation = 0
	WALEntry_DELETE WALEntry_Operation = 1
)

// Enum value maps for WALEntry_Operation.
var (
	WALEntry_Operation_name = map[int32]string{
		0: "UPDATE",
		1: "DELETE",
	}
	WALEntry_Operation_value = map[string]int32{
		"UPDATE": 0,
		"DELETE": 1,
	}
)

func (x WALEntry_Operation) Enum() *WALEntry_Operation {
	p := new(WALEntry_Operation)
	*p = x
	return p
}

func (x WALEntry_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALEntry_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_comm_store_obj_proto_enumTypes[0].Descriptor()
}

func (WALEntry_Operation) Type() protoreflect.EnumType {
	return &file_internal_comm_store_obj_proto_enumTypes[0]
}

func (x WALEntry_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALEntry_Operation.Descriptor instead.
func (WALEntry_Operation) EnumDescriptor() ([]byte, []int) {
	return file_internal_comm_store_obj_proto_rawDescGZIP(), []int{1, 0}
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          uint32                 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_internal_comm_store_obj_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_internal_comm_store_obj_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_internal_comm_store_obj_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Object) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Object) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WALEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            WALEntry_Operation     `protobuf:"varint,1,opt,name=op,proto3,enum=comm.WALEntry_Operation" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Object        *Object                `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Checksum      uint32                 `protobuf:"varint,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_internal_comm_store_obj_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_comm_store_obj_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_internal_comm_store_obj_proto_rawDescGZIP(), []int{1}
}

func (x *WALEntry) GetOp() WALEntry_Operation {
	if x != nil {
		return x.Op
	}
	return WALEntry_UPDATE
}

func (x *WALEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WALEntry) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *WALEntry) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

var File_internal_comm_store_obj_proto protoreflect.FileDescriptor

const file_internal_comm_store_obj_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/comm/store_obj.proto\x12\x04comm\"P\n" +
	"\x06Object\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\rR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xad\x01\n" +
	"\bWALEntry\x12(\n" +
	"\x02op\x18\x01 \x01(\x0e2\x18.comm.WALEntry.OperationR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12$\n" +
	"\x06object\x18\x03 \x01(\v2\f.comm.ObjectR\x06object\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\rR\bchecksum\"#\n" +
	"\tOperation\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01B\x0fZ\rinternal/commb\x06proto3"

var (
	file_internal_comm_store_obj_proto_rawDescOnce sync.Once
	file_internal_comm_store_obj_proto_rawDescData []byte
)

func file_internal_comm_store_obj_proto_rawDescGZIP() []byte {
	file_internal_comm_store_obj_proto_rawDescOnce.Do(func() {
		file_internal_comm_store_obj_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_comm_store_obj_proto_rawDesc), len(file_internal_comm_store_obj_proto_rawDesc)))
	})
	return file_internal_comm_store_obj_proto_rawDescData
}

var file_internal_comm_store_obj_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_comm_store_obj_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_comm_store_obj_proto_goTypes = []any{
	(WALEntry_Operation)(0), // 0: comm.WALEntry.Operation
	(*Object)(nil),          // 1: comm.Object
	(*WALEntry)(nil),        // 2: comm.WALEntry
}
var file_internal_comm_store_obj_proto_depIdxs = []int32{
	0, // 0: comm.WALEntry.op:type_name -> comm.WALEntry.Operation
	1, // 1: comm.WALEntry.object:type_name -> comm.Object
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_comm_store_obj_proto_init() }
func file_internal_comm_store_obj_proto_init() {
	if File_internal_comm_store_obj_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_comm_store_obj_proto_rawDesc), len(file_internal_comm_store_obj_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_comm_store_obj_proto_goTypes,
		DependencyIndexes: file_internal_comm_store_obj_proto_depIdxs,
		EnumInfos:         file_internal_comm_store_obj_proto_enumTypes,
		MessageInfos:      file_internal_comm_store_obj_proto_msgTypes,
	}.Build()
	File_internal_comm_store_obj_proto = out.File
	file_internal_comm_store_obj_proto_goTypes = nil
	file_internal_comm_store_obj_proto_depIdxs = nil
}
